name: hl7_v2
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  recase: 4.1.0

dev_dependencies:
  analyzer: 6.5.0
  build_runner: 2.4.11
  lints: ^4.0.0
  mockito: 5.4.4
  test: 1.25.8
