name: hl7_v2
description: An HL7 v2 message parser and generator, implemented natively in Dart. Allows parsing HL7 v2 messages from their raw string format into a JSON object as well as generating valid HL7 v2 messages from JSON objects.
version: 0.0.1
repository: https://github.com/evoleen/hl7_v2
environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  recase: ^4.1.0

dev_dependencies:
  analyzer: ^6.5.0
  build_runner: 2.4.11
  lints: ^4.0.0
  test: ^1.25.8
